import {
    FiletypeAac,
    FiletypeAi,
    FiletypeBmp,
    FiletypeCs,
    FiletypeCss,
    FiletypeCsv,
    FiletypeDoc,
    FiletypeDocx,
    FiletypeExe,
    FiletypeGif,
    FiletypeHeic,
    FiletypeHtml,
    FiletypeJava,
    FiletypeJpg,
    FiletypeJs,
    FiletypeJson,
    FiletypeJsx,
    FiletypeKey,
    FiletypeM4p,
    FiletypeMd,
    FiletypeMdx,
    FiletypeMov,
    FiletypeMp3,
    FiletypeMp4,
    FiletypeOtf,
    FiletypePdf,
    FiletypePhp,
    FiletypePng,
    FiletypePpt,
    FiletypePptx,
    FiletypePsd,
    FiletypePy,
    FiletypeRaw,
    FiletypeRb,
    FiletypeSass,
    FiletypeScss,
    FiletypeSh,
    FiletypeSql,
    FiletypeSvg,
    FiletypeTiff,
    FiletypeTsx,
    FiletypeTtf,
    FiletypeTxt,
    FiletypeWav,
    FiletypeWoff,
    FiletypeXls,
    FiletypeXlsx,
    FiletypeXml,
    FiletypeYml,
    FileEarmark,
    Folder
} from 'react-bootstrap-icons';

export const icons = {
    'aac': FiletypeAac,
    'ai': FiletypeAi,
    'bmp': FiletypeBmp,
    'cs': FiletypeCs,
    'css': FiletypeCss,
    'csv': FiletypeCsv,
    'doc': FiletypeDoc,
    'docx': FiletypeDocx,
    'exe': FiletypeExe,
    'gif': FiletypeGif,
    'heic': FiletypeHeic,
    'html': FiletypeHtml,
    'java': FiletypeJava,
    'jpg': FiletypeJpg,
    'js': FiletypeJs,
    'json': FiletypeJson,
    'jsx': FiletypeJsx,
    'key': FiletypeKey,
    'm4p': FiletypeM4p,
    'md': FiletypeMd,
    'mdx': FiletypeMdx,
    'mov': FiletypeMov,
    'mp3': FiletypeMp3,
    'mp4': FiletypeMp4,
    'otf': FiletypeOtf,
    'pdf': FiletypePdf,
    'php': FiletypePhp,
    'png': FiletypePng,
    'ppt': FiletypePpt,
    'pptx': FiletypePptx,
    'psd': FiletypePsd,
    'py': FiletypePy,
    'raw': FiletypeRaw,
    'rb': FiletypeRb,
    'sass': FiletypeSass,
    'scss': FiletypeScss,
    'sh': FiletypeSh,
    'sql': FiletypeSql,
    'svg': FiletypeSvg,
    'tiff': FiletypeTiff,
    'tsx': FiletypeTsx,
    'ttf': FiletypeTtf,
    'txt': FiletypeTxt,
    'wav': FiletypeWav,
    'woff': FiletypeWoff,
    'xls': FiletypeXls,
    'xlsx': FiletypeXlsx,
    'xml': FiletypeXml,
    'yml': FiletypeYml,
    'default': FileEarmark,
    "dir": Folder
};
